name: 'ESLint check'
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gnosis/safe-react-eslint-plus-action@v3.5.0
        with:
          issueSummary: true
          issueSummaryType: compact
          issueSummaryMethod: edit
          reportSuggestions: true
          reportIgnoredFiles: true
          reportWarningsAsErrors: true
          configFile: .eslintrc.json
          useEslintrc: true
          npmInstall: true
